# Generated by Django 5.1.2 on 2024-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('last_name', models.CharField(max_length=120, verbose_name='Apellido de Usuario')),
                ('roles', models.CharField(max_length=15, verbose_name='Roll de Usuario')),
                ('username', models.CharField(max_length=15, verbose_name='Alias de Usuario')),
                ('email', models.CharField(max_length=120, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=120, verbose_name='Contraseña')),
                ('status', models.CharField(max_length=15, verbose_name='Estatus')),
                ('create_at', models.CharField(max_length=12, verbose_name='Fecha de Creación')),
                ('update_at', models.CharField(max_length=12, verbose_name='Modificado')),
                ('deleted', models.BooleanField(null=True, verbose_name='Eliminado')),
                ('is_staff', models.IntegerField(null=True, verbose_name='Staff')),
                ('is_active', models.IntegerField(null=True, verbose_name='Esta Activo')),
                ('is_superuser', models.IntegerField(null=True, verbose_name='Super Usuario')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Ultima Actualización')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
                'db_table': 'django_usuario',
                'ordering': ['id'],
            },
        ),
    ]
